name: Basic Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Welcome message
        run: echo "👋 Hello from GitHub Actions!"

      - name: List files
        run: ls -la
