name: Conditional Branch Steps

on:
  push:

jobs:
  conditional-steps:
    runs-on: ubuntu-latest
    env:
      GREETING: "Hello from environment variable!"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Welcome to GitHub Actions!"

      - name: List files
        run: ls -la

      - name: Show main.txt contents
        run: cat main.txt

      - name: Print env variable
        run: echo "${GREETING}"

      - name: Write env var to file
        run: echo "${GREETING}" > greeting.txt

      - name: Combine files
        run: cat main.txt greeting.txt > combined.txt

      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          TOC_TITLE: "## Table of Contents"

      - name: This runs on master only
        if: github.ref == 'refs/heads/master'
        run: echo "✅ You're on master branch!"

      - name: This runs when not on master
        if: github.ref != 'refs/heads/master'
        run: echo "You're NOT on master branch!"

      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          TOC_TITLE: "## Table of Contents"

      - name: This runs on main only
        if: github.ref == 'refs/heads/master'  # Change 'main' to 'master' if your default branch is 'master'
        run: echo "You're on main branch!"

      - name: This runs when not on main
        if: github.ref != 'refs/heads/master'
        run: echo "You're NOT on main branch!"

