name: Scheduled Workflow - Daily Run

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 06:00 UTC
  workflow_dispatch:      # Optional: allows manual triggering

jobs:
  daily-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print scheduled message
        run: echo "✅ This is your scheduled daily run."

      - name: List files
        run: ls -la

      - name: Print current date
        run: date
